### ISSUE TITLE
How to obtain the cookie for origin.js

### ISSUE THREAD

**Issue by rsxdalv** [mygoare/bfban#4]
Hi, thank you for your work!

I'd like to use the origin.js module, however I cannot find which cookies to use, I tried ones from browser (changed the user agent as well) but I get login_required error.

**Comment by mygoare** [comment]
the cookie is used to get the access token, you can see at this line https://github.com/mygoare/bfban/blob/ad9d314d5498d4dfdb397b62e2b1c218973dcb90/server/libs/origin.js#L79

You can try to access the url in your browser after you've signed in your origin account, you will get the access token json data returned.

**Comment by rsxdalv** [comment]
Thank you!
